<?php
  $pageTitle = "Création d'un compte";
  if (isset($_SESSION['compte'])) {
    header("Location:" . HOST . "manage/" . $_SESSION['compte']['identifiant'] . "/dashboard");
  }
?>
<section class="page-section" id="create-compte">
  <div class="container" style="margin-top: 100px;">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading text-uppercase">Créer compte <?= $_GET['identifiant']; ?></h2>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <form id="form" method="POST" action="" enctype="multipart/form-data" novalidate="novalidate">
          <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6 create-compte-form">
              <div class="col-lg-12">  
                <div class="form-group hidden">
                  <input class="form-control" id="idCompte" name="idCompte" type="number" >
                </div>
                <div class="form-group hidden">
                  <input class="form-control" id="identifiant" name="identifiant" type="text" value="<?= $_GET['identifiant']; ?>" readonly>
                  <p class="help-block text-danger"></p>
                </div>
                <?php if ($_GET['identifiant'] == 'entreprise') : ?>
                  <div class="form-group">
                    <i class="fas fa-user-circle icon-input"></i>
                    <input class="form-control" id="nomCreateur" name="nomCreateur" type="text" required="required" data-validation-required-message="Veuillez entrer votre nom *" data-validation-regex-regex="^[a-zA-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð ,.'-]*" data-validation-regex-message="Caractères non valide *" placeholder="Votre nom complet">
                    <p class="help-block text-danger" id="nomCreateur-message"></p>
                  </div>
                  <div class="form-group">
                    <i class="fas fa-envelope icon-input"></i>
                    <input class="form-control text-lowercase" id="mailCreateur" name="mailCreateur" type="mail" required="required" data-validation-required-message="Veuillez entrer votre e-mail *" data-validation-regex-regex="^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])*" data-validation-regex-message="Mail non valide *" placeholder="Votre E-mail">
                    <p class="help-block text-danger" id="mailCreateur-message"></p>
                  </div>
                  <div class="form-group">
                    <i class="fas fa-mobile icon-input"></i>
                      <input class="form-control" id="contactRapide" name="contactRapide" type="text" data-validation-regex-regex="^(00\d{1,2}|\+\d{1,3}|0\d{1,2})?\s?\(?\d{3}\)?[\s.-]?\d{2,3}[\s.-]?\d{2}[\s.-]?\d{2}$" data-validation-regex-message="Contact non valide *" value="" placeholder="Contact rapide">
                      <p class="help-block text-danger" id="contactRapide-message"></p>
                  </div> 
                <?php endif; ?>
                <div class="form-group <?= $_GET['identifiant'] == 'candidat' ? '' : 'd-none';?>">
                  <i class="fas fa-user-circle icon-input"></i>
                  <input class="form-control" id="login" name="login" type="text" required="required" data-validation-required-message="Veuillez entrer votre pseudo *" data-validation-regex-regex="^[a-zA-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð ,.'-]*" data-validation-regex-message="Caractères non valide *" placeholder="Pseudo">
                  <p class="help-block text-danger" id="login-message"></p>
                </div>   
                <div class="form-group <?= $_GET['identifiant'] == 'candidat' ? '' : 'd-none';?>" style="position: relative;">
                  <i class="fas fa-lock icon-input"></i>
                  <input class="form-control" id="motDePasse" name="motDePasse" type="password" required="required" data-validation-required-message="Veuillez entrer votre mot de passe *" data-validation-regex-regex="^.{6,}$" data-validation-regex-message="6 caractères minimum *" placeholder="Mot de passe">
                  <i class="fas fa-eye eye-icon" style="position: absolute; right: 16px; top: 50%; transform: translateY(-50%); z-index: 2;"></i>
                  <p class="help-block text-danger" id="length-message"></p>
                </div>   
                <div class="form-group <?= $_GET['identifiant'] == 'candidat' ? '' : 'd-none';?>" style="position: relative;" >
                  <i class="fas fa-key icon-input"></i>
                  <input class="form-control" id="confirmation" name="confirmation" type="password" required="required" data-validation-required-message="Veuillez confirmer votre mot de passe *" placeholder="Confirmation du mot de passe">
                  <i class="fas fa-eye eye-icon" style="position: absolute; right: 16px; top: 50%; transform: translateY(-50%); z-index: 2;"></i>
                  <p class="help-block text-danger" id="match-message"></p>
                </div>   
                <div class="form-group hidden">
                  <input class="form-control" id="statut" name="statut" type="text" value="active" required="required">
                </div> 
              </div>
              <div class="col-lg-12 text-center">
                <button id="submit" class="btn btn-warning btn-xl" type="submit">
                 Suivant <i class="fas fa-angle-double-right fa-inverse"></i>
                </button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

<script src="<?= HOST; ?>../Web/Ressources/js/creerCompte.js"></script>




<!-- 
    	</div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <form id="form" method="POST" action="" enctype="multipart/form-data" novalidate="novalidate">
          <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6 create-compte-form">
              <div class="col-lg-12">  
                <div class="form-group hidden">
                  <input class="form-control" id="idCompte" name="idCompte" type="number" >
                </div>
                <div class="form-group hidden">
                  <input class="form-control" id="identifiant" name="identifiant" type="text" value="<?= $_GET['identifiant']; ?>" readonly>
                  <p class="help-block text-danger"></p>
                </div>
                <div class="form-group">
                  <i class="fas fa-user-circle icon-input"></i>
                  <input class="form-control" id="nomCreateur" name="nomCreateur" type="text" required="required" data-validation-required-message="Veuillez entrer votre nom *" data-validation-regex-regex="^[a-zA-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð ,.'-]*" data-validation-regex-message="Caractères non valide *" placeholder="Votre nom complet">
                  <p class="help-block text-danger" id="nom-createur"></p>
                </div>
                <div class="form-group">
                  <i class="fas fa-envelope icon-input"></i>
                  <input class="form-control text-lowercase" id="mailCreateur" name="mailCreateur" type="mail" required="required" data-validation-required-message="Veuillez entrer votre e-mail *" data-validation-regex-regex="^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])*" data-validation-regex-message="Mail non valide *" placeholder="Votre E-mail">
                  <p class="help-block text-danger" id="mail-createur"></p>
                </div>
                <div class="form-group">
                  <i class="fas fa-mobile icon-input"></i>
                    <input class="form-control" id="contactRapide" name="contactRapide" type="text" value="" placeholder="Contact rapide">
                    <p class="help-block text-danger"></p>
                </div> 
                <div class="form-group d-none">
                  <i class="fas fa-user-circle icon-input"></i>
                  <input class="form-control" id="login" name="login" type="text" required="required" data-validation-required-message="Veuillez entrer votre pseudo *" data-validation-regex-regex="^[a-z-_]*" data-validation-regex-message="Caractères non valide *" placeholder="Pseudo">
                  <p class="help-block text-danger" id="login-message"></p>
                </div>   
                <div class="form-group d-none">
                  <i class="fas fa-lock icon-input"></i>
                  <input class="form-control" id="motDePasse" name="motDePasse" type="password" required="required" data-validation-required-message="Veuillez entrer votre mot de passe *" data-validation-regex-regex="^.{6,}$" data-validation-regex-message="6 caractères minimum *" placeholder="Mot de passe">
                  <p class="help-block text-danger" id="length-message"></p>
                </div>   
                <div class="form-group d-none">
                  <i class="fas fa-key icon-input"></i>
                  <input class="form-control" id="confirmation" name="confirmation" type="password" required="required" data-validation-required-message="Veuillez confirmer votre mot de passe *" placeholder="Confirmation du mot de passe">
                  <p class="help-block text-danger" id="match-message"></p>
                </div>   
                <div class="form-group hidden">
                  <input class="form-control" id="statut" name="statut" type="text" value="active" required="required">
                </div> 
              </div>
              <div class="col-lg-12 text-center">
              	<button id="submit" class="btn btn-warning btn-xl" type="submit">
          			 Suivant <i class="fas fa-angle-double-right fa-inverse"></i>
          		  </button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

<script src="<?= HOST; ?>../Web/Ressources/js/creerCompte.js"></script>

 -->