<?php
	extract($data);
	$url 		= explode('/', $_GET['page']);
	$id 		= '';
	$loadUrl 	= '';
?>
<section class="page-section" id="back-section">
	<div class="container">
		<?php if (end($url) == 'barometre_list' || end($url) == 'barometre' || end($url) == 'linear_answers_barometer') : ?>
			<div class="row">
				<div class="col-md-3"></div>
				<div class="col-md-6">
					<h4 class="text-center list-title section-heading">Le baromètre</h4>
				</div>
				<?php if (end($url) == 'barometre'  && $_SESSION['compte']['identifiant'] == 'entreprise') : ?>
					<div class="col-md-2 text-right">
						<button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modalEnregistrement" onclick="eventListener()">
							<i class="fa fa-plus" aria-hidden="true"></i>
							<span class="ml-2">créer</span>
						</button>
					</div>
				<?php endif; ?>
			</div>
			<div class="block-section">
				<div class="row">
			        <ul id="new-tab-button">
			        	<?php if ($_SESSION['compte']['identifiant'] == 'entreprise'): ?>
			        		<li id="tab5">
			        			<a href="<?= HOST. 'manage/barometre_list'?>">
			        				La liste du baromètre
			        			</a>
			        		</li>
			        		<li id="tab6">
			        			<a href="<?= HOST. 'manage/barometre'?>">
			        				envoie baromètre
			        			</a>
			        		</li>
			        		<li id="tab8">
			        			<a href="<?= HOST. 'manage/linear_answers_barometer'?>">
			        				Vue global réponse
			        			</a>
			        		</li>
			        	<?php elseif ($_SESSION['compte']['identifiant'] == 'employe') : ?>
			        		<li id="tab7">
			        			<a href="<?= HOST. 'manage/employe/barometre?reply=NO'?>">
			        				La liste du baromètre
			        			</a>
			        		</li>
			        		<li id="tab6">
			        			<a href="<?= HOST. 'manage/employe/barometre?reply=YES'?>">
			        				Mes réponses du baromètre
			        			</a>
			        		</li>
			        		<?php if ($_SESSION['isSuperior']['hasSubordinate'] === 1) : ?>
				        		<li id="tab5">
				        			<a href="<?= HOST. 'manage/barometre_list'?>">
				        				Baromètre de mes collaborateurs
				        			</a>
				        		</li>
				        		<li id="tab8">
				        			<a href="<?= HOST. 'manage/linear_answers_barometer'?>">
				        				Vue global réponse
				        			</a>
				        		</li>
			        		<?php endif; ?>
			        	<?php endif; ?>
			        </ul>
		      	</div>
		      	<?php if (end($url) == 'barometre' && $_SESSION['compte']['identifiant'] == 'entreprise') : $pageTitle = 'Le baromètre' ?>
					<div class="row block-section">
						<div style="position: relative; width: 100%;">
							<table class="table table-striped small-first-col" id="table-back">
								<thead>
									<tr>
										<th></th>
										<th>Libelle</th>	
										<th>Action</th>
									</tr>
								</thead>
								<tbody id="tableSearch" class="body-half-screen">
									<?php if ($listes): ?>
										<?php foreach ($listes as $liste): ?>
											<tr>
												<td></td>
												<td> 
													<?= $liste->getLibelle(); ?>
												</td>
												<td>
													<!-- <a href="detail-barometre?idBarometre=<?=$liste->getIdBarometre() ?>" class="btn btn-info">
											        	<i class="fas fa-eye"></i>
											      	</a>
												  	<a href="update-barometre?idBarometre=<?=$liste->getIdBarometre() ?>" class="btn btn-warning test_click" data-target="#modalUpdate" data-toggle="modal" onclick='updateEvaluation(<?= $liste->getIdBarometre()?>,  "<?= $modifParent[$key]?>", "<?= $modifCateg[$key]?>", this)'>
												        	<i class="fas fa-edit"></i>
												      	</a> -->
													<a href="send-barometre?idBarometre=<?=$liste->getIdBarometre(); ?>"  style="background-color: rgb(35 23 228 / 88%);" class="btn btn-info send" data-target="#modalSendBarometre" data-toggle="modal">
												    	<i class="fas fa-user">envoyer</i>
												  	</a>
											      	<!-- <a href="archive-barometre?idBarometre=<?=$liste->getIdBarometre() ?>" class="btn btn-danger archive" data-toggle="modal" data-target="#confirmationModal" data-id=""
											      		data-url="archive-barometre?idBarometre=<?=$liste->getIdBarometre() ?>">
									                 	<i class="fa fa-times"></i>
									                </a> -->
										   		</td>
											</tr>
										<?php endforeach;?>
									<?php endif;?>
								</tbody>
							</table>
						</div>
					</div>
					<!-- Debut Modal d'envoyer un barometre -->
						<div class="modal fade" id="modalSendBarometre" tabindex="-1" role="dialog" aria-hidden="true">
						  <div class="modal-dialog modal-dialog-centered" role="document">
						    <div class="modal-content">
						      <div class="modal-header">
						        <h5 class="modal-title text-center">Envoie un barmètre</h5>
						        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
						          <span aria-hidden="true">&times;</span>
						        </button>
						      </div>
						      <div class="modal-body">
						      	<div class="form-group">
							        <div class="col-md-8">
										<span class="titre">Liste des employés : </span>
							    		<select  class="selectpicker form-control span3 focus_activated modal-input select-employe" multiple data-live-search="true" required="required" data-validation-required-message="Veuillez sélectionner au moins un employé" id="listIdEmploye">
							    			<!-- <option value="all">Sélectionner Tout</option> -->
							    			<?php foreach ($employes as $employe) : ?>
							    				<option value="<?= $employe->getIdEmploye();?>"><?= $employe->getNom();?>&nbsp;<?= $employe->getPrenom();?></option>
							    			<?php endforeach; ?>
					        			</select>
										<p class="help-block text-danger msg-empty"></p>
									</div>
						      	</div>
						      </div>
						      <div class="modal-footer">
						        <button id="action-envoie" type="submit" class="btn btn-info btn-md" >Valider</button>
						        <button type="button" class="btn btn-danger" data-dismiss="modal">Annuler</button>
						      </div>
						    </div>
						  </div>
						</div>
					<!-- Fin du Modal d'envoyer un barometre -->
					<!-- Debut Modal Ajout nouveau enregistrement -->
						<div class="modal fade" id="modalEnregistrement" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
							<div class="modal-dialog modal-dialog-centered modal-xl" role="document">
								<div class="modal-content">
									<form method="POST" action="<?= HOST . 'manage/create-'. end($url) ; ?>" enctype="multipart/form-data" novalidate="novalidate" class="error">
										<div class="modal-header">
											<div class="text-center" style="width: 100%;">
									      		<h5 class="modal-title" id="exampleModalLabel"> Créer un baromètre</h5>
									      	</div>
											<button type="button" class="close" data-dismiss="modal" aria-label="Close">
												<span aria-hidden="true">&times;</span>
											</button>
										</div>
										<div class="modal-body">
						  					<div class="card p-3" style="background: #efefff;">
												<div class="form-group hidden">
						              				<input class="form-control" name="idBarometre" type="number" value="<?php if(isset($barometre)) :
									              		echo $barometre->getLibelle(); endif; ?>" readonly>
									              	<p class="help-block text-danger"></p>
									            </div>
									            <div class="form-group hidden">
						              				<input class="form-control" name="contentForm" id="hidden-add-contents" type="text" value="">
									              	<p class="help-block text-danger"></p>
									            </div>
												<div class="row" style="margin-bottom: -28px;">
													<div class="col-md-1">
														<span class="titre">Libellé : </span>
													</div>
													<div class="col-md-8">
														<div class="form-group">
															<i class="fa fa-pencil-alt icon-input" aria-hidden="true" style="color: #3a434f; margin-top: 14px;"></i>
															<input class="form-control focus_activated text-capitalize modal-input" id="libelle" name="libelle"
																type="text" required="required" data-validation-required-message="Entrez la libellé svp!"
																data-validation-regex-regex="^[a-zA-Z|éèêëôöîïàùçâ |'-?<>,;:!\/'']*" data-validation-regex-message="Caractères non valide"
																placeholder="Saisir une description">
															<p class="help-block text-danger"></p>
														</div>
													</div>
												</div>
												<hr>
									            <div class="add-periode">
													<div class="row row-period" style="margin-bottom: -28px;">
														<div class="col-md-2">
															<span class="titre">Classement : </span>
														</div>
														<div class="col-md-8 text-center" style="margin-left: -90px">
															<div class="form-group">
																<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
																  	<div class="carousel-inner">
																    	<div class="carousel-item active">
																      		<i class="fa fa-pencil-alt icon-input" aria-hidden="true" style="color: #3a434f; margin-top: 14px; margin-left: -342px;"></i>
																			<input class="form-control focus_activated text-capitalize modal-input" id="periode" name="periode" type="text" required="required" data-validation-required-message="Entrez la classification svp!"
																				data-validation-regex-regex="^[a-zA-Z|éèêëôöîïàùçâ |'-?<>,;:!\/'']*" data-validation-regex-message="Caractères non valide"
																				placeholder="Saisir la classification">
																    	</div>
																 	</div>
																</div>
																<p class="help-block text-danger"></p>
															</div>
														</div>
														<div class="col-md-1 add-btn-period" style="margin-top: -55px; margin-left: 90%;">
															<div class="form-group">
																<button type="button" class="btn btn-add-row-period" onclick="addRowPeriod('ajout', this)" style="background: #6e9e89;width: 33px; height: 33px; margin-left: -10px;" >
																	<i class="fa fa-plus" aria-hidden="false" style="margin: -4px"></i>
																</button>
													  			<button type="button" class="btn btn-delete-row-period hidden" onclick="removeRowPeriod(this)" style="background: #d62037; width: 33px; height: 33px; margin-left: 1px; margin-top: -1px;">
																	<i class="fas fa-times" style="margin: -2px"></i> 
													  			</button>
													  		</div>
														</div>
													</div>
													<hr>
													<div class="add-question">
														<div class="row row-question" style="margin-bottom: -28px; padding-left: 2px;">
															<div class="col-md-1" style="padding-left: 6px;">
																<span class="titre">Question :</span>
															</div>
															<div class="col-md-8">
																<div class="form-group">
																	<textarea class="form-control rounded-0 question" rows="2" placeholder="Saisir une question" style="font-size: 15px!important;"></textarea>
																</div>
															</div>
															<div class="col-md-1 add-btn-question" style="margin-top: -84px; margin-left: 90%;">
																<div class="form-group">
																	<button type="button" class="btn btn-add-row-question" onclick="addRowQuestion('ajout', this)" style="background: #6e9e89;width: 33px; height: 33px; margin-left: -10px;" >
																		<i class="fa fa-plus" aria-hidden="false" style="margin: -4px"></i>
																	</button>
														  			<button type="button" class="btn btn-delete-row-question hidden" onclick="removeRowQuestion(this)" style="background: #d62037; width: 33px; height: 33px; margin-left: 1px; margin-top: -1px;">
																		<i class="fas fa-times" style="margin: -2px"></i> 
														  			</button>
														  		</div>
															</div>
														</div>
														<hr>
														<div class="row" style="margin-bottom: -19px; padding-left: 6px; ">
															<div class="col-md-12 choise-answer">
																<div class="col-md-1" style="padding-left: 6px;">
																	<span class="titre">Choix :</span>
																</div>
																<div class="col-md-11 add-choise" style="margin-bottom: 42px;">
																	<div class="col-md-3" style="margin-top: -33px; margin-left: 6%;">
																		<div class="form-group">
																			<i class="fa fa-pencil-alt icon-input" aria-hidden="true" style="color: #3a434f; margin-top: 16px; margin-left: 5%;"></i>
																				<input class="form-control focus_activated text-capitalize modal-input-choise" type="text" data-validation-regex-regex="^[a-zA-Z|éèêëôöîïàùçâ |'-?<>,;:!\/'']*" data-validation-regex-message="Caractères non valide" placeholder="Réponse prédéfinie"  style="font-size: 14px!important;">
																		</div>
																	</div>
																	<div class="col-md-1 bouton" style="margin-top: -62px; margin-left: 30%;">
																		<div class="form-group">
																			<button type="button" class="btn btn-add-row-choise" onclick="addRowChoise('ajout', this)" style="background: #6e9e89;width: 33px; height: 33px; margin-left: -6px;" >
																				<i class="fa fa-plus" aria-hidden="false" style="margin: -4px"></i>
																			</button>
																  			<button type="button" class="btn btn-delete-row-choise hidden" onclick="removeRowChoise(this)" style="background: #d62037; width: 33px; height: 33px; margin-left: 37px; margin-top: -59px;">
																				<i class="fas fa-times" style="margin: -2px"></i> 
																  			</button>
																  		</div>
																	</div>
																</div>
															</div>
														</div>
														<hr>
														<div class="row row-image" style="margin-bottom: -10px; padding-left: 2px; position: relative;">
															<img class="img-fluid user rounded-circle" id="image" style="height: 80px!important; width: 80px!important;margin-left: 20px; margin-top: -13px;" src="<?= HOST ."../Web/Ressources/images/defaultLogo.png"?>
															">
													        <div class="form-group" style="padding-left: 6px; position: absolute; margin-left: 101px;">
													        	<button class="btn btn-primary" onclick="$('#img-quest').click(); return false;" style="font-size: 14px;">Télécharger une image illustrée cette question </button>
													      		<input class="form-control hidden" id="img-quest" name="img-quest" type="file" accept="image/*" value="">
													        </div>
														</div>
														<hr>
													</div>
													<div class="add-remarque">
														<div class="row row-remarque" style="margin-bottom: -28px; padding-left: 2px;">
															<div class="col-md-1" style="padding-left: 4px;padding-right: 0px;">
																<span class="titre">Remarques :</span>
															</div>
															<div class="col-md-8">
																<div class="form-group">
																	<textarea class="form-control rounded-0 remarque" rows="2" placeholder="Renseigner le remarque (facultatif)" style="font-size: 15px!important;"></textarea>
																</div>
															</div>
														</div>
														<hr>
													</div>
									            </div>
											</div>
										</div>
										<div class="modal-footer">
											<div class="row" style="width: 105%!important;">
									      		<div class="col-md-4">
									      		</div>
									      		<div class="col-md-4" style="margin-bottom: -3%;">
								      				<button type="button" class="btn btn-md btn-danger annuler" data-dismiss="modal" style="height: 44%;">Annuler</button>
									      			<div class="form-group"> 
									      				<button type="submit" class="btn btn-md btn-info" onclick="getAllContents(this)" style="margin-top: -19%; margin-left: 40%;">
									      					Enregister 
									      				</button>
									      			</div>
									      		</div>
									      		<div class="col-md-4">
									      		</div>
									      	</div>
										</div>
									</form>
								</div>
							</div>
						</div>
					<!-- Fin Modal Ajout nouveau enregistrement -->
		      	<?php elseif (end($url) == 'barometre_list' || end($url) == 'linear_answers_barometer') : ?>
		      		<?php $id = end($url) === 'barometre_list' ? 'liste-barometre' : 'linear-liste-barometre';?>
		      		<?php $loadUrl = end($url) === 'barometre_list' ? 'barometre_list' : 'linear_answers_barometer';?>
					<div class="row">
						<div class="col-lg-12">
							<div class="tete-list-section row" style="background: #646c94;">
								<div class="col-md-4" id="filtre-gauche" style="overflow: hidden; white-space: nowrap;">
									<div class="row">
										<div class="col-md-6">
											<select class="select-time" id='filter-group' style="font-size: 0.8em!important;">
												<option value=""> -- groupe --</option>
												<option value="1" <?= $_SESSION['filters']['groupe'] == 1 ? 'selected="selected"' : '';?>>tout</option>
												<option value="2" <?= $_SESSION['filters']['groupe'] == 2 ? 'selected="selected"' : '';?>>par poste</option>
												<option value="4" <?= $_SESSION['filters']['groupe'] == 4 ? 'selected="selected"' : '';?>>par service</option>
											</select>
										</div>
										<div class="col-md-6">
										</div>
									</div>
								</div>
								<div class="col-md-3">
									<label class="titre" style="color: #ffffff;">état : </label>
									<select class="select-time"  style="font-size: 0.8em!important;" id="filter-etat">
										<option value="0" <?= $_SESSION['filters']['etat'] == 0 ? 'selected="selected"' : '';?>>tout</option>
										<option value="1" <?= $_SESSION['filters']['etat'] == 1 ? 'selected="selected"' : '';?>>répondu</option>
										<?php if (end($url) != 'linear_answers_barometer') : ?>
											<option value="2" <?= $_SESSION['filters']['etat'] == 2 ? 'selected="selected"' : '';?>>non répondu</option>
										<?php endif; ?>
									</select>
								</div>
								<div class="col-md-5 text-center" id="filtre-droite">
									<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
									  	<div class="carousel-inner">
									    	<div class="carousel-item active">
									      		<select id="periode" class="select-time"  style="font-size: 0.8em!important;">
													<option value=""> -- période -- </option>
													<option value=0 <?= $_SESSION['filters']['periode'] == 0 ? 'selected="seconds"' : '';?>>tout</option>
													<option value=7 <?= $_SESSION['filters']['periode'] == 7 ? 'selected="seconds"' : '';?>>ce mois</option>
													<option value=3 <?= $_SESSION['filters']['periode'] == 3 ? 'selected="seconds"' : '';?>>hier</option>
													<option value=1 <?= $_SESSION['filters']['periode'] == 1 ? 'selected="seconds"' : '';?>>aujourd'hui</option>
													<!-- <option value=2>demain</option> -->
													<option value=6 <?= $_SESSION['filters']['periode'] == 6 ? 'selected="seconds"' : '';?>>la semaine passée</option>
													<option value=4 <?= $_SESSION['filters']['periode'] == 4 ? 'selected="seconds"' : '';?>>cette semaine </option>
													<!-- <option value=5>la semaine prochaine</option> -->
													<!-- <option value=8>le mois prochain</option> -->
													<option value=9 <?= $_SESSION['filters']['periode'] == 9 ? 'selected="seconds"' : '';?>>le mois passé</option>
												</select>
									    	</div>
									    	<div class="carousel-item">
									      		<label for="datepicker">
										        	<input class="form-control datepicker date-time hasDatepicker" id="debut" type="text" autocomplete="off" placeholder="Début">
									        	</label>
											 	- 
												<label for="datepicker">
										        	<input class="form-control datepicker date-time hasDatepicker" id="fin" type="text" autocomplete="off" placeholder="Fin">
									        	</label>
									    	</div>
									    	<div class="carousel-item">
									    		<?php $date = date('Y') ?>
									      		<select class="select-time" style="width: 200px; font-size: 0.8em!important;" id="selection-month">
									      			<option value="">par mois</option>
									      			<option value="1">Janvier <?=$date?></option>
									      			<option value="2">Février <?=$date?></option>
									      			<option value="3">Mars <?=$date?></option>
									      			<option value="4">Avril <?=$date?></option>
									      			<option value="5">Mai <?=$date?></option>
									      			<option value="6">Juin <?=$date?></option>
									      			<option value="7">Juillet <?=$date?></option>
									      			<option value="8">Août <?=$date?></option>
									      			<option value="9">Septembre <?=$date?></option>
									      			<option value="10">Octobre <?=$date?></option>
									      			<option value="11">Novembre <?=$date?></option>
									      			<option value="12">Décembre <?=$date?></option>
									      		</select>
									    	</div>
									 	</div>
									  	<a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
									    	<span class="carousel-control-prev-icon" aria-hidden="true"></span>
									    	<span class="sr-only">Previous</span>
									  	</a>
									  	<a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
									    	<span class="carousel-control-next-icon" aria-hidden="true"></span>
									    	<span class="sr-only">Next</span>
									  	</a>
									</div>
								</div>
							</div>
							<?php if ($loadUrl == "linear_answers_barometer") : ?>
								<div class="row" style="margin-bottom: -22px; margin-top: 3px;">
									<div class="col-md-3">
			  							<form method="post" action="<?= HOST . 'manage/export_barometer';?>" enctype="multipart/form-data">
											<i class="fas fa-arrow-alt-circle-down" style="margin-left: 3px; margin-top: 7px; position: absolute;"></i>
											<input type="submit" class="btn-success" id="exportCsv" value="Exporter en CSV" style="padding-left: 20px; border-radius: 6%;">
										</form>
									</div>
									<div class="col-md-3"></div>
									<div class="col-md-3"></div>
									<div class="col-md-3">
										<select class="filter-last-date-receive"  style="font-size: 0.8em!important; border-radius: 8%;height: 30px;width: 121px;text-align: left;/* color: #3a434f; */" id="filter-last-date-receive">
										</select>
									</div>
									
								</div>
							<?php endif; ?>
							<div class="container-list-section" id="<?=$id?>" style="background: #f7fbfc;"></div>
						</div>
					</div>
				<?php elseif (end($url) == 'barometre' && $_SESSION['compte']['identifiant'] == 'employe') : $pageTitle = 'Le baromètre' ?>
					<div class="row block-section">
						<div style="position: relative; width: 100%;">
							<table class="table table-striped small-first-col" id="table-back">
								<thead>
									<tr>
										<th></th>
										<th>Libelle</th>
										<?php if ($barometres) : ?>	
											<?php if (!is_null($barometres[0]->getDateReply())) : ?>	
												<th>Reçu le</th>	
												<th>Répondre le</th>	
											<?php else : ?>	
												<th>Date</th>	
											<?php endif; ?>	
										<?php endif; ?>	
										<th>Action</th>
									</tr>
								</thead>
								<tbody id="tableSearch" class="body-half-screen">
									<?php if ($barometres): $indx = 1; ?>
										<?php foreach ($barometres as $barometre): ?>
											<tr>
												<td><?= $indx++; ?></td>
												<td> 
													<?= $barometre->getIdBarometre()->getLibelle(); ?>
												</td>
												<?php if (!is_null($barometre->getDateReply())) : ?>	
													<td> 
														<?= $barometre->getDate(); ?>
													</td>
													<td> 
														<?= $barometre->getDateReply(); ?>
													</td>
												<?php else : ?>	
													<td> 
														<?= $barometre->getDate(); ?>
													</td>
												<?php endif; ?>
												<td>
													<?php if ($barometre->getIsAnswered() == 'YES') : ?>
														<!-- <button type="submit" class="btn btn-info" id="<?=$barometre->getIdBarometreList(); ?>">
												        	Voir ma réponse
												      	</button> -->
													<?php elseif ($barometre->getIsAnswered() == 'NO') : ?>
													  	<button type="button" class="btn btn-info modal-text" data-toggle="modal" data-target="#textModal" id="<?= $barometre->getIdBarometreList(); ?>">
												        	Voir
												      	</button>
													<?php endif; ?>
										   		</td>
											</tr>
										<?php endforeach;?>
									<?php endif;?>
								</tbody>
							</table>
						</div>
					</div>
				<?php endif; ?>
			</div>
			<?php if (isset($barometres) && !empty($barometres)) : ?>
				<!-- Debut Modal du text pour répondre le baromètre -->
					<!-- <div class="modal fade" id="textModal" tabindex="-1" role="dialog" aria-hidden="true">
					  <div class="modal-dialog modal-dialog-centered" role="document">
					    <div class="modal-content">
					      <div class="modal-header">
					        <h5 class="modal-title text-center">L'évaluation du Congrés</h5>
					        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
					          <span aria-hidden="true">&times;</span>
					        </button>
					      </div>
					      <div class="modal-body" style="background-color: white;">
					      	<?php $de = (mb_substr(explode(' ', $barometre->getDate())[1], 0, 1) == 'A' || mb_substr(explode(' ', $barometre->getDate())[1], 0, 1) == 'O') ? "d'" : "de "; ?>
					        <p>
					        	Bonjour à tous,
					        	<br><br>
					        	C'est parti pour "<span><strong><em>l'évaluation du Congrés</em></strong></span>" du mois <?= $de . explode(' ', $barometre->getDate())[1]; ?> . Prenez 5 minutes au maximum pour répondre en toute <mark style="background-color: #f9f80d!important;">sincérité</mark> et de manière <mark style="background-color: #f9f80d!important;">anonyme</mark> à quelques petites questions.
					        	<br><br>
					        	On compte sur vous &#x1F609;
					        	<br><br>
					        	bonne journée!!!
					        </p>
					      </div>
					      <div class="modal-footer">
					        <button type="submit" class="btn btn-info verify" id="<?=$barometre->getIdBarometreList(); ?>">
					        	Je réponds
					      	</button>
					      </div>	
					    </div>
					  </div>
					</div> -->
				<!-- Fin du Modal du text pour répondre le baromètre -->
				
				<!-- Debut Modal du text pour répondre le baromètre -->
					<div class="modal fade" id="textModal" tabindex="-1" role="dialog" aria-hidden="true">
					  <div class="modal-dialog modal-dialog-centered" role="document">
					    <div class="modal-content">
					      <div class="modal-header">
					        <h5 class="modal-title text-center">Happy Place To Work</h5>
					        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
					          <span aria-hidden="true">&times;</span>
					        </button>
					      </div>
					      <div class="modal-body" style="background-color: white;">
					      	<?php $de = (mb_substr(explode(' ', $barometre->getDate())[1], 0, 1) == 'A' || mb_substr(explode(' ', $barometre->getDate())[1], 0, 1) == 'O') ? "d'" : "de "; ?>
					        <p>
					        	Bonjour à tous,
					        	<br><br>
					        	C'est parti pour le baromètre "<span><strong><em>Happy Place To Work</em></strong></span>" du mois <?= $de . explode(' ', $barometre->getDate())[1]; ?> . Prenez 5 minutes au maximum pour répondre en toute <mark style="background-color: #f9f80d!important;">sincérité</mark> et de manière <mark style="background-color: #f9f80d!important;">anonyme</mark> à quelques petites questions.
					        	<br><br>
					        	On compte sur vous &#x1F609;
					        	<br><br>
					        	bonne journée!!!
					        </p>
					      </div>
					      <div class="modal-footer">
					        <button type="submit" class="btn btn-info verify" id="<?=$barometre->getIdBarometreList(); ?>">
					        	Je réponds
					      	</button>
					      </div>	
					    </div>
					  </div>
					</div>
				<!-- Fin du Modal du text pour répondre le baromètre -->
			<?php endif; ?>
			<!-- Debut Modal de confirmation -->
				<div class="modal fade" id="confirmationModal" tabindex="-1" role="dialog" aria-hidden="true">
				  <div class="modal-dialog modal-dialog-centered" role="document">
				    <div class="modal-content">
				      <div class="modal-header">
				        <h5 class="modal-title text-center">Confirmation</h5>
				        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
				          <span aria-hidden="true">&times;</span>
				        </button>
				      </div>
				      <div class="modal-body">
				        <p id="text-confirmation"></p>
				      </div>
				      <div class="modal-footer">
				        <a id="action-confirmation" class="btn btn-success">Oui</a>
				        <button type="button" class="btn btn-danger deney-modal" data-dismiss="modal">Non</button>
				      </div>	
				    </div>
				  </div>
				</div>
			<!-- Fin du Modal de confirmation -->
			<!-- Debut Modal de répondre un baromètre -->
				<div class="modal fade" id="responseBarometerModal" tabindex="-1" role="dialog" aria-hidden="true">
				  <div class="modal-dialog modal-dialog-centered modal-lg" role="dialog">
				    <div class="modal-content">
				      <div class="modal-header" style="background: linear-gradient(to bottom, #F29430 0%, #ffb100 100%)!important;align-items: center;margin-bottom: -16px;">
				        <h5 class="modal-title text-center" style="color: #ffffff!important;">Ma réponse</h5>
				      </div>
				      <div class="modal-body">
				        <div id="text-responseBarometer">
				        	<!-- ce body est généré par jquery dans listeBarometre.js -->
				        </div>
				      </div>
				      <div class="modal-footer">
				        <a id="action-responseBarometer" class="btn btn-success">Valider ma réponse</a>
				      </div>	
				    </div>
				  </div>
				</div>
			<!-- Fin du Modal de répondre un baromètre -->
			<?php if (!isset($loadUrl)) :
				$loadUrl = 'barometre_list';?>
			<?php endif;?>
			<?php if (!isset($id)) :
				$listId = 'liste-barometre';?>
			<?php endif;?>
			<script type="text/javascript">
				var loadUrl = "<?= $loadUrl;?>";
				var	listId 	= "<?= $id;?>";
				var offSet 	= <?= !is_null($_SESSION['filters']['offset']) ? $_SESSION['filters']['offset'] : 1;?>;
			</script>
			<link rel="stylesheet" href="<?= HOST; ?>../Web/Ressources/css/plugin/bootstrap-select.min.css" />
			<script src="<?= HOST; ?>../Web/Ressources/js/listeBarometre.js"></script>
		<?php endif; ?>
	</div>
</section>
<link rel="stylesheet" href="<?= HOST; ?>../Web/Ressources/css/plugin/bootstrap-select.min.css" />
<script src="<?= HOST; ?>../Web/Ressources/js/plugin/bootstrap-select.min.js"></script>
<script src="<?= HOST; ?>../Web/Ressources/js/plugin/jquery.dataTables.min.js"></script>
<script src="<?= HOST; ?>../Web/Ressources/js/plugin/datatable.js"></script>
<script src="<?= HOST; ?>../Web/Ressources/js/plugin/dataTables.responsive.js"></script>
<script src="<?= HOST; ?>../Web/Ressources/js/plugin/cleave.js"></script>
<script src="<?= HOST; ?>../Web/Ressources/js/plugin/cleave-phone.i18n.js"></script>
<script src="<?= HOST; ?>../Web/Ressources/js/tabBarometre.js"></script>
<script src="<?= HOST; ?>../Web/Ressources/js/backend_datatable.js"></script>