 <!-- Header -->
  <header class="masthead">
    <div class="container">
      <div class="intro-text">
        <div class="intro-lead-in">Bienvenue sur le site 
          <img class="rounded-circle img-fluid" id="smile" src="<?= HOST; ?>../Web/Ressources/images/smile.jpg">
        </div>
        <div class="intro-heading text-uppercase">
          Human Cart'<img class="rounded-circle img-fluid" id="office" src="<?= HOST; ?>../Web/Ressources/images/logowebsite.png">ffice
        </div>
      </div>
    </div>
  </header>
  <section class="bg-light page-section">
    <div id="conge" style="width:100%; height: 100px;"></div>
    <div class="container custom-container">
      <div class="row">
        <div class="col-lg-12 text-center" style="display: flex;">
          <img class="rounded-circle img-fluid image" src="<?= HOST; ?>../Web/Ressources/images/gif/light-bulb-flashes.gif" style="width: 10%;">
          <h2 class="section-heading text-uppercase">&nbsp;&nbsp;&nbsp;&nbsp;Fonctionnalité de congé</h2>
        </div>
      </div>
      <div class="row align-items-center" style="margin-top: 4%;">
        <div class="col-sm-6">
          <video id="movie" width="100%" height="auto" preload controls>
            <source src="<?= HOST; ?>../Web/Ressources/videos/Pack-conge-presentation-dentreprise_free.mp4" type='video/mp4; codecs=avc1.42E01E, mp4a.40.2"' />
            <source src="<?= HOST; ?>../Web/Ressources/videos/Pack-conge-presentation-dentreprise_free.mp4" type='video/webm; codecs="vp8, vorbis"' />
            <source src="<?= HOST; ?>../Web/Ressources/videos/Pack-conge-presentation-dentreprise_free.mp4" type='video/ogg; codecs="theora, vorbis"' />
            <object width="100%" height="auto" type="application/x-shockwave-flash" data="flowplayer-3.2.1.swf">
              <param ... />
            </object>
          </video>
          <!-- <div class="cover">
            <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-calendar-conge.png" alt="" style="width: 100%;">
          </div> -->
        </div>
        <div class="col-sm-5 offset-1">
          <span class="timeline-panel">
            <p class="text-muted " style="">
              <i class="fa fa-user"></i>&nbsp;
              <strong>Demande de congé</strong>
              <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-calendar-check.png" alt="">
            </p>
          </span>
          <span class="timeline-panel">
            <p class="text-muted ">
              <i class="fa fa-user"></i>&nbsp;
              <strong>Validation du congé</strong>
              <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-check.png" alt="" style="width: 11%;">
            </p>
          </span>
          <span class="timeline-panel">
            <p class="text-muted ">
              <strong>Notification par email</strong>
              <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-envelop.png" alt="" style="width: 14%;">
            </p>
          </span>
          <span class="timeline-panel">
            <p class="text-muted ">
              <strong>Planning du congés</strong>
              <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-calendar-check.png" alt="">&nbsp;
              <i class="fa fa-users" style="margin-top: 7%;"></i>
            </p>
          </span>
          <span class="timeline-panel">
            <p class="text-muted ">
              <strong>Solde du congé</strong>
              <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-solde-conge.png" alt="" style="width: 15%;">
            </p>
          </span>
          <span class="timeline-panel">
            <p class="text-muted ">
              <strong>Paramétrage</strong>
              <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-setting-conge.png" alt="" style="width: 15%;">
            </p>
          </span>
        </div>
      </div>
    </div>
  </section>
  <hr>
  <section class="bg-light page-section">
    <div id="paie-avance" style="width:100%; height: 100px;"></div>

    <div class="container custom-container">
      <div class="row">
        <div class="col-lg-12 text-center" style="display: flex;">
          <img class="rounded-circle img-fluid image" src="<?= HOST; ?>../Web/Ressources/images/gif/light-bulb-flashes.gif" style="width: 10%;">
          <h2 class="section-heading text-uppercase">&nbsp;&nbsp;&nbsp;&nbsp;Fonctionnalité de paie et d'avance</h2>
        </div>
      </div>
      <div class="row align-items-center" style="margin-top: 4%;">
        <div class="col-sm-5 offset-1">
          <span class="timeline-panel">
            <p class="text-muted " style="margin-top: -19%;">
              <strong>Collecte de l'ensemble des données de la paie et de l'avantage</strong>
              <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-paid-info.png" alt="" style="width: 36%;">
            </p>
          </span>
          <span class="timeline-panel">
            <p class="text-muted" style="margin-top: -19%;">
              <strong>Calcul</strong>
              <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-calculate-paied.png" alt="" style="width: 30%;">
            </p>
          </span>
          <span class="timeline-panel">
            <p class="text-muted" style="margin-top: -19%;">
              <strong>Fiche de paie</strong>
              <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-print-paied.png" alt="" style="width: 33%;">
            </p>
          </span>
          <span class="timeline-panel">
            <p class="text-muted" style="margin-top: -6%;">
              <strong>Demande d’avance</strong>
              <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-avance.png" alt="" style="width: 13%;">
            </p>
          </span>
          <span class="timeline-panel">
            <p class="text-muted" style="margin-top: -9%;">
              <strong>Historiques</strong>
              <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-history.png" alt="" style="width: 23%;">
            </p>
          </span>
          <span class="timeline-panel">
            <p class="text-muted" style="margin-top: -11%;">
              <strong>Paramétrage</strong>
              <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-paied-parameter.jpg" alt="" style="width: 17%;">
            </p>
          </span>
        </div>
        <div class="col-sm-6">
          <div class="cover">
            <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-paid.png" alt="" style="width: 75%; margin-left: 15%;">
          </div>
        </div>
      </div>
    </div>
  </section>
  <hr>
  <section class="bg-light page-section">
    <div id="permission" style="width:100%; height: 100px;"></div>

    <div class="container custom-container">
      <div class="row">
        <div class="col-lg-12 text-center" style="display: flex;">
          <img class="rounded-circle img-fluid image" src="<?= HOST; ?>../Web/Ressources/images/gif/light-bulb-flashes.gif" style="width: 10%;">
          <h2 class="section-heading text-uppercase">Fonctionnalité de permission et de repos</h2>
        </div>
      </div>
      <div class="row align-items-center" style="margin-top: 4%;">
        <div class="col-sm-6">
          <div class="cover">
            <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-permission.png" alt="" style="width: 62%; margin-left: 17%;">
          </div>
        </div>
        <div class="col-sm-5 offset-1">
          <span class="timeline-panel">
            <p class="text-muted " style="">
              <i class="fa fa-user"></i>&nbsp;
              <strong>Demande du permission et de repos</strong>
              <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-calendar-check.png" alt="">
            </p>
          </span>
          <span class="timeline-panel">
            <p class="text-muted ">
              <i class="fa fa-user"></i>&nbsp;
              <strong>Validation du permission et de repos</strong>
              <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-check.png" alt="" style="width: 11%;">
            </p>
          </span>
          <span class="timeline-panel">
            <p class="text-muted ">
              <strong>Notification par email</strong>
              <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-envelop.png" alt="" style="width: 10%;">
            </p>
          </span>
          <span class="timeline-panel">
            <p class="text-muted ">
              <strong>Modification jours fériés</strong>
              <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-public-holidays.jpg" alt="">
            </p>
          </span>
          <span class="timeline-panel">
            <p class="text-muted ">
              <strong>Paramétrage</strong>
              <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-parameter.png" alt="" style="width: 9%;">
            </p>
          </span>
        </div>
      </div>
    </div>
  </section>
  <hr>
  <section class="bg-light page-section">
    <div id="pointage" style="width:100%; height: 100px;"></div>
    <div class="container custom-container">
      <div class="row">
        <div class="col-lg-12 text-center" style="display: flex;">
          <img class="rounded-circle img-fluid image" src="<?= HOST; ?>../Web/Ressources/images/gif/light-bulb-flashes.gif" style="width: 10%;">
          <h2 class="section-heading text-uppercase">&nbsp;&nbsp;&nbsp;&nbsp;Fonctionnalité de pointage </h2>
        </div>
      </div>
      <div class="row align-items-center" style="margin-top: 4%;">
        <div class="col-sm-5 offset-1">
          <span class="timeline-panel">
            <p class="text-muted " style="">
              <strong>Présence</strong>
              <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-be-here.png" alt="" style="width: 20%;">
            </p>
          </span>
          <span class="timeline-panel">
            <p class="text-muted "style="margin-top: -5%;">
              <strong>TAF</strong>
              <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-realised.png" alt="" style="width: 11%;">
            </p>
          </span>
          <span class="timeline-panel">
            <p class="text-muted " style="margin-top: -5%;">
              <strong>Traking du temps</strong>
              <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-looped.png" alt="" style="width: 22%;">
            </p>
          </span>
          <span class="timeline-panel">
            <p class="text-muted " style="margin-top: -6%;">
              <strong>Suivi</strong>
              <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-istocked.jpg" alt="" style="width: 15%;">
            </p>
          </span>
        </div>
        <div class="col-sm-6">
          <div class="cover">
            <img src="<?= HOST; ?>../Web/Ressources/images/icon/icone-presence.png" alt="" style="width: 65%; margin-left: 16%;">
          </div>
        </div>
      </div>
    </div>
    <hr>
  </section>
  <script type="text/javascript">
    var url = new URL(window.location.href);
    if (url.hash == '#conge') {
      console.log($('#movie').promise().state())
      $('#movie')[0].play();
    }
  </script>