<!-- Header -->
    <header class="masthead">
        <div class="container">
            <div class="intro-text">
              <div class="intro-lead-in">Bienvenue sur le site 
                <img class="rounded-circle img-fluid" id="smile" src="<?= HOST; ?>../Web/Ressources/images/smile.jpg">
              </div>
              <div class="intro-heading text-uppercase">
                Human Cart'<img class="rounded-circle img-fluid" id="office" src="<?= HOST; ?>../Web/Ressources/images/logowebsite.png">ffice
              </div>
              <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="https://hco.mg/apropos/">A propos de HCO</a>
            </div>
        </div>
      </header>