<?php
	$pageTitle= "Solutions";
?>
<!-- Header -->
  <header class="masthead">
    <div class="container">
      <div class="intro-text">
        <div class="intro-lead-in">Bienvenue sur le site 
          <img class="rounded-circle img-fluid" id="smile" src="<?= HOST; ?>../Web/Ressources/images/smile.jpg">
        </div>
        <div class="intro-heading text-uppercase">
          Human Cart'<img class="rounded-circle img-fluid" id="office" src="<?= HOST; ?>../Web/Ressources/images/logowebsite.png">ffice
        </div>
        <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="https://hco.mg/apropos/">À propos de HCO</a>
      </div>
    </div>
  </header>
  <section class="bg-light page-section" id="solutions">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading text-uppercase">Solutions</h2>
          <h3 class="section-subheading text-muted">
          </h3>
        </div>
      </div>
      <div class="row align-center">
        <div class="col-md-6">
          <a href="<?= HOST;?>Solution/gestionTalents">
            <span class="timeline-panel">
              <img class="rounded-circle img-fluid image" src="<?= HOST; ?>../Web/Ressources/images/gif/gestion-talents.gif">
              <p class="text-muted" style="color: #021e40fa!important; font-size: 24px;margin-top: -12%;margin-left: 19%;">
                <strong>GESTION DE TALENTS</strong>
              </p>
            </span>
          </a>
          <br>
          <br>
          <h5 class="service-heading">Que signifie gestion des talents ?</h5>
          <p class="text-muted">
            La gestion des talents au sein d’une entreprise consiste à acquérir et retenir des collaborateurs, et à investir dans le capital humain qu’ils représentent. Il s’agit donc d’embaucher des profils compétents, de les fidéliser afin qu’ils restent dans l’entreprise, et de développer leurs compétences afin de les exploiter à leur plein potentiel. 
            <br>
            Ces logiciels sont généralement modulables et se focalisent sur les problématiques suivantes :</p>
          <ul class="timeline-body" style="margin-left: 20%;">
            <li>Gestion de capital humain</li>
            <li>Evaluation</li>
            <li>Barometre</li>
          </ul>
        </div>
        <div class="col-md-6">
          <a  href="<?= HOST;?>Solution/adminPersonnel">
            <span class="timeline-panel">
              <img class="img-fluid image" src="<?= HOST; ?>../Web/Ressources/images/gif/admin-personnel.gif">
              <p class="text-muted" style="color: #021e40fa!important; font-size: 24px;margin-top: -12%;margin-left: 19%;">
                <strong>ADMINISTRATION DE PERSONNEL</strong>
              </p>
            </span>
          </a>
          <br>
          <br>
          <h5 class="service-heading">Qu'est-ce qu'un logiciel d'administration du personnel ?</h5>
          <p class="text-muted"> 
            Véritables couteaux suisses, les logiciels d’administration du personnel (ou de gestion administrative du personnel) sont des outils permettant de centraliser les données RH et de fluidifier les échanges entre le service RH et les employés. 
            <br>
            Ces logiciels sont généralement modulables et se focalisent sur les problématiques suivantes :
          </p>
          <ul class="timeline-body" style="margin-left: 20%;">
            <li>Gestion de pointage</li>
            <li>Gestion de temps d’absence</li>
            <li>Gestion de paie et de prestation social </li>
          </ul>
        </div>
      </div>
    </div>
  </section>
