<?php
	$url = explode('-', $_GET['page']);
?>
<section class="page-section" id="back-section">
    <div class="container">
      	<div class="row">
        	<div class="col-lg-12">
          		<form id="form" method="POST" action="<?= HOST. "manage/save-" . $url[1];?>" enctype="multipart/form-data" novalidate="novalidate">
	                <?php if ($url[1] == "jourFerie" && !empty($data)): $pageTitle = "Enregistrement d'un jour férié"; extract($data); ?>        
				    	<div class="row">
					        <div class="col-lg-12 text-center">
					          	<h5><?= $pageTitle; ?></h5>
					        </div>
				      	</div>
				      	<div class="row">
				      		<div class="col-md-3"></div>
				      		<div class="col-md-5 block-div" style="margin-left: 50px; border-radius: 5px;">
				      			<div class="form-group">
				      				<input type="hidden" name="idJourFerie" value="<?= $jourFerie->getIdJourFerie(); ?>" >
				      			</div>
				      			<div class="form-group">
				      				<label class="label-input"> Designation : </label>
				      				<input class="form-control focus_activated" name="designation" type="text" value="<?= $jourFerie->getDesignation();?>" required="required" data-validation-required-message="Veuillez entrer une designation">
			                  		<p class="help-block text-danger"></p>
				      			</div>
				      		</div>
				      	</div>
				    <?php elseif ($url[1] == "permission" && !empty($data)): $pageTitle = "Enregistrement d'une permission"; extract($data); ?>
				    	<div class="row">
					        <div class="col-lg-12 text-center">
					          	<h5><?= $pageTitle; ?></h5>
					        </div>
				      	</div>
				      	<div class="row">
				      		<div class="col-md-3"></div>
				      		<div class="col-md-5 block-div" style="margin-left: 50px; border-radius: 5px;">
				      			<div class="form-group">
				      				<input type="hidden" name="idTypePermission" value="<?= $permission->getIdTypePermission(); ?>" >
				      			</div>
				      			<div class="form-group">
				      				<label class="label-input"> Permission : </label>
				      				<input class="form-control focus_activated" name="designation" type="text" value="<?= $permission->getDesignation();?>" required="required" data-validation-required-message="Veuillez entrer la permission">
			                  		<p class="help-block text-danger"></p>
				      			</div>
				      		</div>
				      	</div>
				    <?php endif ?>
				    <div class="col-lg-12 text-center">
	                	<div id="success"></div>
	                	<button id="submit" class="btn btn-info btn-xl" type="submit">
	                		Enregistrer
	                	</button>
	                	<a class="btn btn-danger btn-xl cancel" href="#" data-toggle="modal" data-target="#cancelModal" data-url="<?= 'cancel-' . $url[1]; ?>">Annuler</a>          	
	              	</div>
				</form>
			</div>
		</div>
	</div>
</section>
<!-- Modal -->
<div class="modal fade" id="cancelModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-center">Confirmation</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p id="text-confirmation"></p>
      </div>
      <div class="modal-footer">
        <a id="action-cancel" class="btn btn-success">Oui</a>
        <button type="button" class="btn btn-danger" data-dismiss="modal">Non</button>
      </div>
    </div>
  </div>
</div>
<script src="<?= HOST; ?>../Web/Ressources/js/plugin/cleave.js"></script>
<script src="<?= HOST; ?>../Web/Ressources/js/plugin/cleave-phone.i18n.js"></script>
<script src="<?= HOST; ?>../Web/Ressources/js/afficherFormEmploye.js"></script>
<script> 
	var pathname = new URL(window.location.href).pathname; 
	var cleave = new Cleave('#input-phone', {
      phone:true,
      phoneRegionCode: $('#select-country').children("option:selected").val()
    });
	if ($('#select-country').children("option:selected").val() == "") {
    	$('#input-phone').addClass('hidden');
    }
	$('#select-country').change(function(){
		if ($('#select-country').children("option:selected").val() == "") {
	    	$('#input-phone').addClass('hidden');
	    } else {
			$('#input-phone').removeClass('hidden');
	      	cleave.setPhoneRegionCode(this.value);
	      	cleave.setRawValue('');
	    }
    });
</script>