<?php extract($data); ?>
<link href="<?= HOST; ?>../Web/Ressources/js/templateShift.css" rel="stylesheet">

    <link href="https://cdn.syncfusion.com/ej2/20.4.48/ej2-base/styles/material.css" rel="stylesheet">
    <link href="https://cdn.syncfusion.com/ej2/20.4.48/ej2-buttons/styles/material.css" rel="stylesheet">
    <link href="https://cdn.syncfusion.com/ej2/20.4.48/ej2-calendars/styles/material.css" rel="stylesheet">
    <link href="https://cdn.syncfusion.com/ej2/20.4.48/ej2-dropdowns/styles/material.css" rel="stylesheet">
    <link href="https://cdn.syncfusion.com/ej2/20.4.48/ej2-inputs/styles/material.css" rel="stylesheet">
    <link href="https://cdn.syncfusion.com/ej2/20.4.48/ej2-navigations/styles/material.css" rel="stylesheet">
    <link href="https://cdn.syncfusion.com/ej2/20.4.48/ej2-popups/styles/material.css" rel="stylesheet"> 
    <link href="https://cdn.syncfusion.com/ej2/20.4.48/ej2-schedule/styles/material.css" rel="stylesheet">
<script src="<?= HOST; ?>../Web/Ressources/js/plugin/ej2CHART.min.js" type="text/javascript"></script>
<div>
	<div class="graph">
		<div class="row row-graph" style="background: #fff; border-bottom: 20px solid #17a2b8; border-radius: 0px 0px 5px 5px; margin-right: -20px; margin-left: -20px;">
			<div class="col-md-6"  id="trakindTask" style="left: 13px;">
		        <div id='element' style="z-index: 1; top: 62px; left: -12px;"></div>
		        <div id="element2" style="top: -450px; left: -12px;"></div>
		        <table class="table table-striped" style="top: -448px; left: 0px; position: relative; font-size: 12px; display: flex; flex-flow: wrap;">
					<thead style="display: table; width: 701px; background: #64978a70;">
						<tr>
							<th style="width: 12%;">date</th>
							<th style="width: 28%;">titre</th>
							<th style="width: 40%;">description</th>
							<th class="text-center" style="width: 13%;">temps passé</th>
							<th class="text-center" style="width: 7%;">ratio temps</th>
						</tr>
					</thead>
					<tbody id="list-taskes" style="max-height: 1000px; overflow: auto; display: block; width: 701px;">
						<?php foreach ($taches as $group) : extract($group); ?>
							<tr style="background: #878b8ab5;">
								<td class="text-center">Cumul</td>
								<td class="text-center"></td>
								<td class="text-center" style="width: 40%;"> <span class="text-important" > <?= is_object($groupe) ? $groupe->getDescription() : "Indéfinie"; ?></span></td>
								<td class="text-center" style="width: 19%;">
									<span class="text-important">
										<?= isset($tracking) ? $tracking['hour'] . 'h ' . $tracking['minute'] . 'min ' . $tracking['second'] . 'sec' : "N/A";?>
									</span>
								</td>
								<td class="text-center" style="width: 10%;">
									<span class="text-important">
										<?= ($ratio) ? $ratio . '%' : "N/A";?>
									</span>
								</td>
							</tr>
							<?php foreach ($tache as $key => $value) : ?>
								<?php if (array_key_exists($key, $durees)) : ?>
									<tr>
										<td class="text-center" style="width: 12%;"> <span class="text-important"> <?= !empty($durees[$key]) ? (array_key_exists($key, $dates) ? $dates[$key] : '000-00-00'): '000-00-00';?></span></td>
										<td class="text-important description" style="width: 28%;"><?= $value->getTitre() ?></td>
										<td style="width: 40%;"><?= $value->getDescription() ?></td>
										<td class="text-center" style="width: 13%;">
											<?php if (!empty($durees[$key])) : ?>
												<span class="text-important">	
													<?= $durees[$key]['hour'] . 'h'?>
													<?= substr('0' . $durees[$key]['minute'], -2) . 'min';?>
												</span>
											<?php else : ?>
												<p class="text-important">N/A</p>
											<?php endif ?>
										</td>
										<td class="text-center" style="width: 7%;">
											<span class="text-important">
												<?= array_key_exists($key, $ratios) ? $ratios[$key] . '%' : "N/A";?>
											</span>
										</td>
									</tr>
								<?php endif ?>
							<?php endforeach ?>
						<?php endforeach ?>
					</tbody>
					<tfoot style="display: table; width: 701px;">
						<tr style="background: #647994; color: #ffffff;">
							<td></td>
							<td colspan="2" class="text-important">TOTAL</td>
							<td style="width: 50%;"></td>
							<td class="text-center">
								<span class="text-important">
									<?= $tempsTotal['hour'] . 'h ' . substr('0' . $tempsTotal['minute'], -2) . 'min ' . $tempsTotal['second'] . 'sec';?>
								</span>
							</td>
							<td></td>
						</tr>
					</tfoot>
				</table>
			</div>
			<div class="col-md-6">
		        <div id='journey'></div>	
		        <div id='journey-time' style="height:300px;"></div>
		        <div id="legend" style="position: relative;" >
			        <table class="table table-striped" id='render-workedMin' style="position: absolute; width: 247px; font-size: 12px;">
						<thead>
							<tr>
								<th>MINIMUM</th>
								<th></th>
							</tr>
						</thead>
						<tbody style="overflow: auto; max-height: 429px; display: block;">
						</tbody>
					</table>
			        <table class="table table-striped" id='render-workedMoy' style="position: absolute; width: 247px; font-size: 12px; top: 0; left: 224px;">
						<thead>
							<tr>
								<th>MOYENNE</th>
								<th></th>
							</tr>
						</thead>
						<tbody style="overflow: auto; max-height: 429px; display: block;">
						</tbody>
					</table>
			        <table class="table table-striped" id='render-workedMax' style="position: absolute; width: 247px; font-size: 12px; top: 0; left: 471px;">
						<thead>
							<tr>
								<th>MAXIMUM</th>
								<th></th>
							</tr>
						</thead>
						<tbody style="overflow: auto; max-height: 429px; display: block;">
						</tbody>
					</table>
		        	
		        </div>
			</div>
		</div>

		<!-- /**@changelog 2022/02/20 [EVOL] (Lansky) Fixer l'entête et scroll juste en bas du block section */ -->
			<input type="hidden" id="mois" value="<?=date('Y-m');?>">
			<input type="hidden" id="filter-group" value="4">
			<input type="hidden" id="fin" value=>
			<!-- <div class="row" style="height: 60vh; overflow: auto;">
				<div class="col-md-9 card p-2" style="white-space: nowrap; /* overflow: scroll; *//* height: calc(100vh - 329px); */position: relative; margin-top: -4px;">
					<div class="p-0 m-0" id="container-dates" style="position: sticky; top: 0;z-index: 1000;background: var(--white);"></div>
					<div id="container-contenus" class="p-0 m-0" style="min-height: 300px;">
						<div class="text-center" style="width: 100%; height:300px;">
							<i class="fa fa-spinner fa-pulse fa-5x fa-fw" style="margin-top: 100px; color: #647994;"></i>
							<span class="sr-only">Loading...</span>
						</div>
					</div>
				</div>
			</div> -->

		<div class="row row-planning-conge"></div>
	</div>
</div>

<script>
	var ele = document.getElementById('container');
	var datas = <?php echo json_encode($data); ?> ;
	if(ele) {
	    ele.style.visibility = "visible";
	}
</script>
