<?php
  $pageTitle= "Gestion de talents";
?>
 <!-- Header -->
  <header class="masthead">
    <div class="container">
      <div class="intro-text">
        <div class="intro-lead-in">Bienvenue sur le site 
          <img class="rounded-circle img-fluid" id="smile" src="<?= HOST; ?>../Web/Ressources/images/smile.jpg">
        </div>
        <div class="intro-heading text-uppercase">
          Human Cart'<img class="rounded-circle img-fluid" id="office" src="<?= HOST; ?>../Web/Ressources/images/logowebsite.png">ffice
        </div>
      </div>
    </div>
  </header>
  <section class="bg-light page-section" id="gestion-talents">
    <div class="container custom-container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <img class="rounded-circle img-fluid image" src="<?= HOST; ?>../Web/Ressources/images/gif/gestion-talents.gif"  style="margin-bottom: -10%; margin-left: -57%; width: 10%; height: 100%;">
          <h2 class="section-heading text-uppercase">Gestion de talents</h2>
        </div>
      </div>
      <div class="row align-items-center" style="margin-top: 4%; margin-bottom: 67px; padding-top: 45px;">
        <div class="col-sm-5 col-text">
          <div class="cover-gound" style="--imageBack: url(<?= HOST; ?>../Web/Ressources/images/icon/icone-barometer.png);">
          </div>
          <div class="row-content">
            <span class="timeline-panel">
              Module<br>
              <p class="text-muted strong ">
                <strong>Baromètre</strong>
              </p>
              <img class="rounded-circle img-fluid image" src="<?= HOST; ?>../Web/Ressources/images/gif/emoj-bôf.gif" style="--size: 50px!important; --top: -28%">
            </span>
            <ul>
              <li><a href="#"><p>Mes baromètres</p></a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-1"></div>
        <div class="col-sm-5 col-text">
          <div class="cover-gound" style="--imageBack: url(<?= HOST; ?>../Web/Ressources/images/icon/icone-find-valide.jpg);">
          </div>
         <div class="row-content">
           <span class="timeline-panel">
            Module<br>
            <p class="text-muted strong ">
              <strong>Évaluation</strong>
            </p>
            <img class="rounded-circle img-fluid image" src="<?= HOST; ?>../Web/Ressources/images/gif/eval-checkmarks.gif" style="--size: 83px!important; --top: -28%">
          </span>
          <ul>
            <li><a href=""><p>Mes évaluations</p></a></li>
            <li><a href=""><p>Créer une évaluation</p></a></li>
            <li><a href=""><p>Gérer mes formulaires d'évaluations</p></a></li>
          </ul>
         </div>
        </div>
      </div>
      <div class="row align-items-center" style="margin-top: 4%; margin-bottom: 67px; padding-top: 45px;">
        <div class="col-sm-5 col-text" style="height: 34vh!important;">
          <div class="cover-gound" style="--imageBack: url(<?= HOST; ?>../Web/Ressources/images/icon/icone-assurance-capital-humain.png);">
          </div>
          <div class="row-content">
            <span class="timeline-panel">
              Module<br>
              <p class="text-muted strong ">
                <strong>Gestion de capital humain</strong>
              </p>
              <img class="rounded-circle img-fluid image" src="<?= HOST; ?>../Web/Ressources/images/gif/vr-RH.gif" style="--size: 50px!important; --top: -28%">
            </span>
            <ul>
              <li><a href="#"><p>Contrat</p></a></li>
              <li><a href="#"><p>Employés</p></a></li>
              <li><a href="#"><p>Poste</p></a></li>
              <li><a href="#"><p>Service</p></a></li>
              <li><a href="#"><p>Formation</p></a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-1"></div>
        <div class="col-sm-5 col-text" style="height: 34vh!important;">
          <div class="cover-gound" style="--imageBack: url(<?= HOST; ?>../Web/Ressources/images/icon/icone-recrutement.jpg);">
          </div>
         <div class="row-content">
           <span class="timeline-panel">
            Module<br>
            <p class="text-muted strong ">
              <strong>Recrutement</strong>
            </p>
            <img class="rounded-circle img-fluid image" src="<?= HOST; ?>../Web/Ressources/images/gif/anim-find-users.gif" style="--size: 83px!important; --top: -28%">
          </span>
          <ul>
            <li><a href="#"><p>Entretiens</p></a></li>
            <li><a href="#"><p>Mes candidats</p></a></li>
            <li><a href="#"><p>Offres</p></a></li>
            <li><a href="#"><p>Tests</p></a></li>
          </ul>
         </div>
        </div>
      </div>
      <br>
      <hr>
      <div class="row" style="margin-top: 4%;">
        <div class="col-md-4">
          <div class="row">
            <i><img class="rounded-circle img-fluid image" src="<?= HOST; ?>../Web/Ressources/images/icon/icone-manager.jpg" style="width: 130px!important; height: 130px!important; margin-left: 90%;"></i>
            <p class="text-muted text-center" style="color: #021e40fa!important; font-size: 24px;margin-top: 37%;">
              <strong>Manager</strong>
            </p>
          </div>
          <div class="row">
            <ul class="timeline-body" style="/*margin-left: 20%;*/ font-size: 1.3rem;">
              <li style="display: flex; flex-direction: row-reverse; align-items: baseline;">
                <p>Est acteur de la montée en compétences de son équipe</p>&nbsp;
                <i class="fa fa-check" style="color: #00c853;" aria-hidden="true"></i>
              </li>
              <li style="display: flex; flex-direction: row-reverse; align-items: baseline;">
                <p>Est force de proposition dans le management du capital humain de l'entreprise</p>&nbsp;
                <i class="fa fa-check" style="color: #00c853;" aria-hidden="true"></i>
              </li>
              <li style="display: flex; flex-direction: row-reverse; align-items: baseline;">
                <p>Renforce le lien et sa connaissance de ses collaborateurs</p>&nbsp;
                <i class="fa fa-check" style="color: #00c853;" aria-hidden="true"></i>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-4">
          <div class="row">
            <i><img class="rounded-circle img-fluid image" src="<?= HOST; ?>../Web/Ressources/images/icon/icone-salarie.png" style="width: 130px!important; height: 130px!important; margin-left: 90%;"></i>
            <p class="text-muted text-center" style="color: #021e40fa!important; font-size: 24px;margin-top: 37%;">
              <strong>Salarié</strong>
            </p>
          </div>
          <div class="row">
            <ul class="timeline-body" style="font-size: 1.3rem;">
              <li style="display: flex; flex-direction: row-reverse; align-items: baseline;">
                <p>Identifie ses compétences et celles attendues pour son poste</p>&nbsp;
                <i class="fa fa-check" style="color: #00c853;" aria-hidden="true"></i>
              </li>
              <li style="display: flex; flex-direction: row-reverse; align-items: baseline;">
                <p>A une visibilité sur les processus et évolutions de carrière possibles</p>&nbsp;
                <i class="fa fa-check" style="color: #00c853;" aria-hidden="true"></i>
              </li>
              <li style="display: flex; flex-direction: row-reverse; align-items: baseline;">
                <p>Se projette à plus long terme dans l'entreprise</p>&nbsp;
                <i class="fa fa-check" style="color: #00c853;" aria-hidden="true"></i>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-4">
          <div class="row">
            <i><img class="rounded-circle img-fluid image" src="<?= HOST; ?>../Web/Ressources/images/icon/icone-service-RH.png" style="width: 130px!important; height: 130px!important; margin-left: 90%;"></i>
            <p class="text-muted text-center" style="color: #021e40fa!important; font-size: 24px;margin-top: 37%;">
              <strong>Service RH</strong>
            </p>
          </div>
          <div class="row">
            <ul class="timeline-body" style="font-size: 1.3rem;">
              <li style="display: flex; flex-direction: row-reverse; align-items: baseline;">
                <p>A une vision à 360° des collaborateurs</p>&nbsp;
                <i class="fa fa-check" style="color: #00c853;" aria-hidden="true"></i>
              </li>
              <li style="display: flex; flex-direction: row-reverse; align-items: baseline;">
                <p>Anticipe les besoins en compétences, formations et recrutements</p>&nbsp;
                <i class="fa fa-check" style="color: #00c853;" aria-hidden="true"></i>
              </li>
              <li style="display: flex; flex-direction: row-reverse; align-items: baseline;">
                <p>Pilote le management des talents et le développement des compétences de l'entreprise</p>&nbsp;
                <i class="fa fa-check" style="color: #00c853;" aria-hidden="true"></i>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
 </section>