<div class="menu-titre">
   <button class="btn btn-sm btn-transparent text-left" type="button" data-toggle="collapse" data-target="#collapseMenu1" aria-expanded="false" aria-controls="collapseExample" style="color: #000;">
    	MES ACTIVITES
  	</button>
</div>
<div class="collapse m-0 p-0" id="collapseMenu1">
  	<div class="m-0 p-0">
    	<div class="item menu-niv-1" id="item1">
        	<a class="lien-menu" href="<?= HOST;?>manage/candidatures">Candidatures envoyées</a>
    	</div>
    	<div class="item menu-niv-1" id="item2">
        	<a class="lien-menu" href="<?= HOST;?>manage/suggest_offres">Offres suggérées</a>
    	</div>
    	<div class="item menu-niv-1" id="item3">
        	<a class="lien-menu" href="<?= HOST;?>offres">Offres disponibles</a>
    	</div>
  	</div>
</div>
<script src="<?= HOST; ?>../Web/Ressources/js/menuCandidat.js"></script>