<div class="menu-titre">
    <button class="btn btn-sm btn-transparent text-dark text-left" id="btn-titre-1" type="button" data-toggle="collapse" data-target="#collapseMenu1" aria-expanded="false" aria-controls="collapseExample">
        <i class="fa fa-caret-right fas" id="titre-1"></i>
        <span class="ml-2">COMPTES</span>
    </button>
</div>
<div class="collapse m-0 p-0" id="collapseMenu1">
    <div class="m-0 p-0">
        <div class="item menu-niv-1" id="item1">
            <a href="<?= HOST; ?>manage/superadmins" class="lien-menu">Administrateur</a>
        </div>
        <div class="item menu-niv-1" id="item2">
            <a href="<?= HOST; ?>manage/activeEntreprises" class="lien-menu">Entreprise</a>
        </div>
        <div class="item menu-niv-1" id="item3">
            <a href="<?= HOST; ?>manage/activeCandidats" class="lien-menu">Candidat</a>
        </div>
        <div class="item menu-niv-1" id="item4">
            <a href="<?= HOST; ?>manage/emails_contacts" class="lien-menu">Contact</a>
        </div>
        <div class="item menu-niv-1">
            Archives
        </div>
        <div class="item menu-niv-2" id="item5">
            <a class="lien-menu" href="<?= HOST; ?>manage/archiveEntreprises">Entreprise</a>
        </div>
        <div class="item menu-niv-2" id="item6">
            <a class="lien-menu" href="<?= HOST; ?>manage/archiveCandidats">Candidat</a>
        </div>
        <div class="item menu-niv-1" id="item7">
            <a href="<?= HOST; ?>manage/historiques" class="lien-menu">Historique</a>
        </div>
    </div>
</div>
<div class="menu-titre">
    <button class="btn btn-sm btn-transparent text-dark text-left" id="btn-titre-2" type="button" data-toggle="collapse" data-target="#collapseMenu2" aria-expanded="false" aria-controls="collapseExample">
        <i class="fa fa-caret-right fas" id="titre-2"></i>
        <span class="ml-2">RECRUTEMENT</span>
    </button>
</div>
<div class="collapse m-0 p-0" id="collapseMenu2">
    <div class="m-0 p-0">
        <div class="item menu-niv-1" id="item8">
            <a class="lien-menu" href="<?= HOST; ?>manage/domaines">Domaine</a>
        </div>
        <div class="item menu-niv-1" id="item9">
            <a class="lien-menu" href="<?= HOST; ?>manage/personnalites">Personnalité</a>
        </div>
        <div class="item menu-niv-1" id="item10">
            <a class="lien-menu" href="<?= HOST; ?>manage/services">Service</a>
        </div>
        <div class="item menu-niv-1" id="item11">
            <a class="lien-menu" href="<?= HOST; ?>manage/postes">Poste</a>
        </div>
        <div class="item menu-niv-1" id="item12">
            <a class="lien-menu" href="<?= HOST; ?>manage/contrats">Contrat</a>
        </div>
        <div class="item menu-niv-1" id="item13">
            <a class="lien-menu" href="<?= HOST; ?>manage/niveaux_experiences">Niveau d'expérience</a>
        </div>
        <div class="item menu-niv-1" id="item14">
            <a class="lien-menu" href="<?= HOST; ?>manage/niveaux_etudes">Niveau d'étude</a>
        </div>
    </div>
</div>
<div class="menu-titre">
    <button class="btn btn-sm btn-transparent text-dark text-left" type="button" id="btn-titre-3" data-toggle="collapse" data-target="#collapseMenu3" aria-expanded="false" aria-controls="collapseExample">
        <i class="fa fa-caret-right fas" id="titre-3"></i>
        <span class="ml-2">ADMINISTRATION</span>
    </button>
</div>
<div class="collapse m-0 p-0" id="collapseMenu3">
    <div class="m-0 p-0">
        <div class="item menu-niv-1" id="item15">
            <a class="lien-menu" href="<?= HOST; ?>manage/banques">Banque</a>
        </div>
        <div class="item menu-niv-1" id="item20">
            <a class="lien-menu" href="<?= HOST; ?>manage/admin/templateContrat">Template de contrat</a>
        </div>
        <div class="item menu-niv-1" id="item16">
            <a class="lien-menu" href="<?= HOST; ?>manage/categorieProfessionnelles">Catégorie Professionnelle</a>
        </div>
        <div class="item menu-niv-1" id="item17">
            <a class="lien-menu" href="<?= HOST; ?>manage/jourFeries">Jours fériés</a>
        </div>
        <div class="item menu-niv-1" id="item18">
            <a class="lien-menu" href="<?= HOST; ?>manage/permissions">Permissions</a>
        </div>
        <div class="item menu-niv-1" id="item19">
            <a class="lien-menu" href="<?= HOST; ?>manage/tachePlanifiees">Tâches Planifiées</a>
        </div>
    </div>
</div>
<script src="<?= HOST; ?>../Web/Ressources/js/menuAdmin.js"></script>
 