<?php
	extract($data);
	$url = explode('/', $_GET['page']);
?>
<section class="page-section" id="back-section">
	<div class="container">
		<div class="row" style="margin-top: -15px;">
			<div class="col-md-2"></div>
			<div class="col-md-8">
					<h4 class="text-center list-title section-heading">Edition de fiche paie</h4>
			</div>
			<div class="col-md-2 text-right">
				
			</div>
		</div>
		<div class="block-section">

		</div>
	</div>
</section>