<div>
	<table class="table table-borderless" id="table-contrat" style="width: 100%; font-size: 0.9em; border : none;">
		<thead>
			<tr class="p-0">
				<th class="p-0 text-left"><div class="card p-2 m-1 card-grey">Nom et Prénom</div></th>
				<th class="p-0 text-center th-pointage"><div class="card-pointage card p-2 m-1 card-grey">Action</div></th>
			</tr>
		</thead>
		<tbody class="" style="padding: 0px!important;"> 
			<?php foreach ($data as $datum) : extract($datum);?>
				<tr class="p-0">
					<td class="text-important p-0 text-left">
						<div class="card p-2 m-1 card-light-grey emp-<?=$employe->getIdEmploye();?>" style="height: 40px; max-height: 40px;">
							<span class=""><?= $employe->getNom() . ' ' . $employe->getPrenom();?></span>
						</div>
					</td>
					<td class="p-0 text-important text-center" style="width: 20%;">
						<div class="card p-2 m-1 card-light-grey" style="height: 40px; max-height: 40px;">
							<div class="row">
								<div class="col-md-1 ml-1">
									
								</div>
								<div class="col-md-1 ml-1">
									
				                </div>
				                <div class="col-md-1 ml-1">
				                	
			                	</div>
			                	<div class="col-md-1 ml-1">
			                		
		                        </div>
							</div>
						</div>
					</td>
				</tr>
				<?php if ($contratEmploye != null) : ?>
					<script>
						$('document').ready(function(){
							<?php if ($employe->getPhoto() != "") : ?>
								photo = "<?= HOST . '../Web/Ressources/images/employes/' . $employe->getPhoto() ?>";
							<?php else : ?>
								photo = "<?= HOST . '../Web/Ressources/images/profilCandidat.png' ?>";
							<?php endif ?>
							contentHtml = "<div class='row' style='width: 400px;'>" + 
											"<div class='col-md-2'>" + 
												"<img src=" + photo + " style='height: 50px; width: 50px;'>" +
											"</div>" +
											"<div class='col-md-10'>" +
												"<span><?=$employe->getNom() . ' ' . $employe->getPrenom()?><span/></br>" + 
												"<span><?=$service?><span/></br>" +
												"<span><?=$poste?><span/></br>" +
												"<span><?=$categorie?><span/></br>" +
											"</div>" +
										"</div>";
							setHtmlTippy('emp-<?=$employe->getIdEmploye()?>', contentHtml);
						});
					</script>
				<?php endif ?>
			<?php endforeach ?>
		</tbody>
	</table>
</div>
<script>
	$('document').ready(function(){
		$('#table-contrat').DataTable( {
	        "pagingType" : "full_numbers",
	        "language" : {
		        "search" : "_INPUT_",
		        "searchPlaceholder" : "rechercher",
		        "zeroRecords": "Aucune donnée disponible",
	            "oPaginate": {
	                "sFirst":    "Premier",
	                "sLast":    "Dernier",
	                "sNext":    "Suivant",
	                "sPrevious": "Précédent"
	            }
		    },
	        "searchPlaceholder" : "rechercher",
	        "lengthMenu" : [[10, 25, 50, -1], [10, 25, 50, "All"]]
	    } );
	    $('#table-contrat_length').addClass("invisible");
	    $('#table-contrat_info').parent().removeClass();
	    $('#table-contrat_info').parent().addClass("col-md-3");
	    $('#table-contrat_info').remove();
	    $('#table-contrat_wrapper').css("padding","0px");

	});
	function setHtmlTippy(classTippy, contentTippy)
	{
		var attente = setTimeout(function() {
			tippy('.' + classTippy, {
				content: contentTippy,
				allowHtml : true,
				placement : 'top-start'
	  		});	
		}, 1000);
	}
	tippy('.fa-info-circle', {
		content: "Les détails du contrat"
	});
	tippy('.fa-plus-circle', {
		content: "Nouveau contrat"
	});
	tippy('.fa-print', {
		content: "Imprimer le contrat"
	});
	tippy('.fa-history', {
		content: "L'historique des contrats"
	});
</script>